######################################################################
# Automatically generated by qmake (3.0) Fr. Aug. 9 03:24:19 2019
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += . include src

# Input
HEADERS += include/view.hpp
SOURCES += src/view.cpp
